### ISSUE TITLE
.site-header.featured-image Causes Horizontal Scrolling on latest Chrome and Firefox

### ISSUE THREAD

**Issue by myspoonistoobig** [dustinleer/wordcamp-lancaster-2019#1]
Setting overflow: visible in .site-header.featured-image has a side effect with min-width: 100vw on pages like https://2019.lancasterpa.wordcamp.org/contact/ where it causes horizontal scrolling.

**Comment by dustinleer** [comment]
Thank you for reporting the issue, we'll get on fixing this.
